"""Telegram remote-control bot — raw ``getUpdates`` polling (spec 4.2, 5.3).

Runs as a single pass inside an ephemeral GitHub Actions job (bot-poll.yml,
every 5 minutes): fetch updates >= persisted offset, dispatch commands,
respond, persist the new offset, exit. No long-lived process, no framework.

RESPONSIBILITY: the bot owns only Telegram I/O. EVERY reply is generated by
the Lead Agent (src/agents/lead_agent.py) — one Gemini brain that manages and
assigns tasks to the six-agent team (Atlas, Scout, Enrichment, Outreach,
Followups, Inbound).
"""
from __future__ import annotations

import asyncio
import logging
import time

import httpx

from src.agents.github_agent import GitHubAgent
from src.agents.lead_agent import LeadAgent
from src.bot.commands import is_allowed
from src.core.config import Settings
from src.core.llm import GeminiClient, GeminiPool, LLMUsage
from src.core.state import StateStore

log = logging.getLogger(__name__)

TELEGRAM_API = "https://api.telegram.org"


# ---------- low-level Telegram API ----------
# Transport errors MUST never crash the poll job: a transient ConnectError /
# ReadTimeout on 2026-08-14 (run 31766417723) propagated uncaught out of
# get_updates, failed the whole bot-poll job, and broke the keep-alive chain.
# Both helpers retry transient failures (transport errors + 429/5xx) with
# backoff and degrade to [] / False on final failure instead of raising.
_RETRY_ATTEMPTS = 3
_RETRY_BASE_SEC = 1.5


async def _retry_sleep(attempt: int) -> None:
    """Exponential backoff: 1.5s, 3s before the retry at ``attempt`` 0/1."""
    await asyncio.sleep(_RETRY_BASE_SEC * (2 ** attempt))


def _transient_status(code: int) -> bool:
    """429 (flood control) and 5xx (server hiccup) are worth a retry."""
    return code == 429 or code >= 500


async def get_updates(token: str, offset: int, timeout: int = 50) -> list[dict]:
    """Long-poll getUpdates. ``timeout`` is Telegram's long-poll seconds
    (0-50); the HTTP client allows a little extra for the server response.

    Resilient: transient failures (ConnectError, ReadTimeout, 429, 5xx) are
    retried with backoff; a permanent failure logs and returns [] so the poll
    pass ends cleanly and the keep-alive chain dispatches the next run."""
    url = f"{TELEGRAM_API}/bot{token}/getUpdates"
    params = {"offset": offset, "timeout": timeout,
              "allowed_updates": '["message"]'}
    for attempt in range(_RETRY_ATTEMPTS):
        try:
            async with httpx.AsyncClient(timeout=max(15, timeout + 10)) as client:
                resp = await client.get(url, params=params)
        except httpx.HTTPError as exc:
            if attempt < _RETRY_ATTEMPTS - 1:
                log.warning("getUpdates transport error (attempt %d): %s",
                            attempt + 1, exc)
                await _retry_sleep(attempt)
                continue
            log.warning("getUpdates unreachable after %d attempts: %s",
                        _RETRY_ATTEMPTS, exc)
            return []
        if resp.status_code == 200:
            return resp.json().get("result", [])
        if _transient_status(resp.status_code) and attempt < _RETRY_ATTEMPTS - 1:
            log.warning("getUpdates HTTP %s (attempt %d); retrying",
                        resp.status_code, attempt + 1)
            await _retry_sleep(attempt)
            continue
        log.warning("getUpdates failed: %s %s", resp.status_code, resp.text[:200])
        return []
    return []


async def send_message(token: str, chat_id: int, text: str) -> bool:
    for chunk in _chunk(text, 4096):
        if not await _send_chunk(token, chat_id, chunk):
            return False
    return True


async def _send_chunk(token: str, chat_id: int, text: str) -> bool:
    """Send one <=4096-char chunk with retry/backoff; never raises."""
    url = f"{TELEGRAM_API}/bot{token}/sendMessage"
    payload = {"chat_id": chat_id, "text": text}
    for attempt in range(_RETRY_ATTEMPTS):
        try:
            async with httpx.AsyncClient(timeout=15) as client:
                resp = await client.post(url, json=payload)
        except httpx.HTTPError as exc:
            if attempt < _RETRY_ATTEMPTS - 1:
                log.warning("sendMessage transport error (attempt %d): %s",
                            attempt + 1, exc)
                await _retry_sleep(attempt)
                continue
            log.warning("sendMessage unreachable after %d attempts: %s",
                        _RETRY_ATTEMPTS, exc)
            return False
        if resp.status_code == 200:
            return True
        if _transient_status(resp.status_code) and attempt < _RETRY_ATTEMPTS - 1:
            log.warning("sendMessage HTTP %s (attempt %d); retrying",
                        resp.status_code, attempt + 1)
            await _retry_sleep(attempt)
            continue
        log.warning("sendMessage failed: %s", resp.text[:200])
        return False
    return False


def _chunk(text: str, size: int) -> list[str]:
    return [text[i:i + size] for i in range(0, len(text), size)] or [""]


# ---------- response generation (all owned by the Lead Agent) ----------
def _make_lead(settings: Settings, state: StateStore, github: GitHubAgent,
               llm: GeminiClient | None = None) -> LeadAgent:
    return LeadAgent(settings, state, github=github, llm=llm)


async def _dispatch_command(
    command: str,
    args: str,
    user_id: int,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
) -> str:
    """Execute one whitelisted command via the Lead Agent (shared by the
    exact-slash fast path AND the Gemini brain)."""
    return await _make_lead(settings, state, github).delegate(command, args, user_id)


def _pro_brain(settings: Settings) -> GeminiPool:
    """Lead Agent brain: pro model tier, load-split across both Gemini keys,
    with automatic FAILOVER — a quota-exhausted key or model falls through to
    the other key, then the always-current alias — so Gemini never silently
    stops replying. Per-call recording for the /usage dashboard command."""
    return GeminiPool(settings, role="pro", usage=LLMUsage(settings.state_dir))


async def _handle_free_text(
    text: str,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
    user_id: int = 0,
    llm: GeminiClient | None = None,
) -> str:
    """Route free text through the Lead Agent's Gemini intent brain."""
    if llm is None:
        llm = _pro_brain(settings)
    return await _make_lead(settings, state, github, llm=llm)._handle_free_text(text, user_id)


async def handle_update(
    update: dict,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
) -> None:
    """Process one update: authorization, then the Lead Agent owns the reply."""
    message = update.get("message") or {}
    chat_id = message.get("chat", {}).get("id")
    user_id = message.get("from", {}).get("id")
    text = message.get("text", "")
    if chat_id is None or user_id is None:
        return
    if not is_allowed(user_id, settings.admin_telegram_ids):
        log.info("ignoring message from unauthorized user %s", user_id)
        return

    lead = _make_lead(settings, state, github, llm=_pro_brain(settings))
    reply = await lead.handle_message(text, user_id)
    await send_message(settings.telegram_bot_token, chat_id, reply)


# ---------- single poll pass ----------
async def poll_once(settings: Settings, state: StateStore, github: GitHubAgent) -> int:
    """Long-poll Telegram for up to ``poll_max_wait_sec`` and process every
    update that arrives, then return.

    Deliberately bounded, NOT an infinite loop: each pass is a short-lived
    job (bot-poll.yml), so after the listening window we exit cleanly and the
    keep-alive dispatches the next run. One broken update (e.g. a GitHub 403
    reply) is caught and skipped so it can never abort the pass.
    """
    token = settings.telegram_bot_token
    if not token:
        log.error("TELEGRAM_BOT_TOKEN not set")
        return 0
    offset = int(state.get("telegram_offset", "offset", 0))
    deadline = time.monotonic() + settings.poll_max_wait_sec
    processed = 0
    consecutive_failures = 0
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break
        # Telegram caps long-poll at 50s; use the rest of our budget per call.
        timeout = int(min(50, max(2, remaining)))
        try:
            updates = await get_updates(token, offset, timeout=timeout)
        except Exception:  # final safety net: never let the network layer fail the job
            log.exception("getUpdates raised; treating as empty poll")
            updates = []
        new = 0
        for update in updates:
            update_id = int(update.get("update_id", 0))
            # Skip ONLY updates strictly below the offset. Telegram returns
            # unconfirmed updates with update_id >= offset, so an update whose
            # id EQUALS the stored offset is still unconfirmed and must be
            # processed — skipping it (update_id <= offset) leaves it stuck in
            # the Telegram queue forever (the stuck 704228564 /run bug).
            if update_id < offset:
                continue
            try:
                await handle_update(update, settings, state, github)
            except Exception:  # never let one update crash the pass
                log.exception("update %s failed", update_id)
            # Telegram confirms an update only when the NEXT offset is strictly
            # greater than it. Storing update_id itself leaves the last update
            # perpetually pending, so a stale repo offset (push race) re-fetches
            # and re-runs it — the duplicate /run dispatch bug. +1 confirms it.
            offset = max(offset, update_id + 1)
            new += 1
            processed += 1
        if new:
            state.set("telegram_offset", "offset", offset)
        # A dead/invalid token returns [] instantly on every call — bail after
        # 3 consecutive empty polls instead of burning the whole window.
        if not updates:
            consecutive_failures += 1
            if consecutive_failures >= 3:
                log.error("getUpdates returning empty repeatedly; token issue? "
                          "giving up this poll pass")
                break
        else:
            consecutive_failures = 0
    return processed


async def main() -> int:
    import src.core.logging as logmod
    logmod.setup_logging()
    settings = Settings.load()
    if not settings.admin_telegram_ids:
        log.warning(
            "ADMIN_TELEGRAM_IDS is empty: the bot is OPEN, any chat with the "
            "link can send commands (use /id to fetch your user ID)"
        )
    state = StateStore(settings.state_dir)
    github = GitHubAgent(settings, state)
    # Keep-alive FIRST: queue the next poll run before we long-poll, so even a
    # job timeout mid-window can't starve the chain. Guarded so the cron +
    # keep-alive combination can't compound the queue — skip when a run is
    # already queued or in progress.
    if settings.poll_keepalive and not await github.bot_poll_pending():
        msg = await github.trigger_bot_poll()
        log.info("keep-alive: %s", msg)
    # Single pass: process whatever batch is pending, persist the offset, then
    # exit — no tight polling loop, so the Actions job always terminates.
    processed = await poll_once(settings, state, github)
    # Commit + push state (approvals decisions, telegram_offset) so the next
    # ephemeral job — and the pipeline — actually sees them. Without this, the
    # files written here vanish when the job ends and /approve would never
    # reach the outreach run.
    if processed and github.commit_state():
        log.info("state committed to repo")
    log.info("poll pass finished; processed %d update(s); exiting", processed)
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
