"""Telegram remote-control bot — raw ``getUpdates`` polling (spec 4.2, 5.3).

Runs as a single pass inside an ephemeral GitHub Actions job (bot-poll.yml,
every 5 minutes): fetch updates >= persisted offset, dispatch commands,
respond, persist the new offset, exit. No long-lived process, no framework.

RESPONSIBILITY: the bot owns only Telegram I/O. EVERY reply is generated by
the Lead Agent (src/agents/lead_agent.py) — one Gemini brain that manages and
assigns tasks to the six-agent team (Atlas, Scout, Enrichment, Outreach,
Followups, Inbound).
"""
from __future__ import annotations

import asyncio
import logging

import httpx

from src.agents.github_agent import GitHubAgent
from src.agents.lead_agent import LeadAgent
from src.bot.commands import is_allowed
from src.core.config import Settings
from src.core.llm import GeminiClient, GeminiPool
from src.core.state import StateStore

log = logging.getLogger(__name__)

TELEGRAM_API = "https://api.telegram.org"


# ---------- low-level Telegram API ----------
async def get_updates(token: str, offset: int) -> list[dict]:
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.get(
            f"{TELEGRAM_API}/bot{token}/getUpdates",
            params={"offset": offset, "timeout": 2,
                    "allowed_updates": '["message"]'},
        )
        if resp.status_code != 200:
            log.warning("getUpdates failed: %s %s", resp.status_code, resp.text[:200])
            return []
        return resp.json().get("result", [])


async def send_message(token: str, chat_id: int, text: str) -> bool:
    for chunk in _chunk(text, 4096):
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                f"{TELEGRAM_API}/bot{token}/sendMessage",
                json={"chat_id": chat_id, "text": chunk},
            )
        if resp.status_code != 200:
            log.warning("sendMessage failed: %s", resp.text[:200])
            return False
    return True


def _chunk(text: str, size: int) -> list[str]:
    return [text[i:i + size] for i in range(0, len(text), size)] or [""]


# ---------- response generation (all owned by the Lead Agent) ----------
def _make_lead(settings: Settings, state: StateStore, github: GitHubAgent,
               llm: GeminiClient | None = None) -> LeadAgent:
    return LeadAgent(settings, state, github=github, llm=llm)


async def _dispatch_command(
    command: str,
    args: str,
    user_id: int,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
) -> str:
    """Execute one whitelisted command via the Lead Agent (shared by the
    exact-slash fast path AND the Gemini brain)."""
    return await _make_lead(settings, state, github).delegate(command, args, user_id)


def _pro_brain(settings: Settings) -> GeminiPool:
    """Lead Agent brain: pro model tier, load-split across both Gemini keys."""
    clients = [GeminiClient(settings.gemini_api_key, settings.gemini_model_pro)]
    if settings.gemini_api_key_2:
        clients.append(GeminiClient(settings.gemini_api_key_2, settings.gemini_model_pro))
    return GeminiPool(clients=clients)


async def _handle_free_text(
    text: str,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
    user_id: int = 0,
    llm: GeminiClient | None = None,
) -> str:
    """Route free text through the Lead Agent's Gemini intent brain."""
    if llm is None:
        llm = _pro_brain(settings)
    return await _make_lead(settings, state, github, llm=llm)._handle_free_text(text, user_id)


async def handle_update(
    update: dict,
    settings: Settings,
    state: StateStore,
    github: GitHubAgent,
) -> None:
    """Process one update: authorization, then the Lead Agent owns the reply."""
    message = update.get("message") or {}
    chat_id = message.get("chat", {}).get("id")
    user_id = message.get("from", {}).get("id")
    text = message.get("text", "")
    if chat_id is None or user_id is None:
        return
    if not is_allowed(user_id, settings.admin_telegram_ids):
        log.info("ignoring message from unauthorized user %s", user_id)
        return

    lead = _make_lead(settings, state, github, llm=_pro_brain(settings))
    reply = await lead.handle_message(text, user_id)
    await send_message(settings.telegram_bot_token, chat_id, reply)


# ---------- single poll pass ----------
async def poll_once(settings: Settings, state: StateStore, github: GitHubAgent) -> int:
    """Fetch + process ONE batch of updates, then return.

    Deliberately NOT an infinite loop: each poll pass is a short-lived job
    (bot-poll.yml runs every 5 minutes), so after the batch is processed we
    exit cleanly. One broken update (e.g. a GitHub 403 reply) is caught and
    skipped so it can never abort the whole pass.
    """
    token = settings.telegram_bot_token
    if not token:
        log.error("TELEGRAM_BOT_TOKEN not set")
        return 0
    offset = int(state.get("telegram_offset", "offset", 0))
    updates = await get_updates(token, offset)
    processed = 0
    for update in updates:
        update_id = int(update.get("update_id", 0))
        if update_id <= offset:
            continue
        try:
            await handle_update(update, settings, state, github)
        except Exception:  # never let one update crash the batch
            log.exception("update %s failed", update_id)
        offset = max(offset, update_id)
        processed += 1
    if processed:
        state.set("telegram_offset", "offset", offset)
    return processed


async def main() -> int:
    import src.core.logging as logmod
    logmod.setup_logging()
    settings = Settings.load()
    if not settings.admin_telegram_ids:
        log.warning(
            "ADMIN_TELEGRAM_IDS is empty: the bot is OPEN, any chat with the "
            "link can send commands (use /id to fetch your user ID)"
        )
    state = StateStore(settings.state_dir)
    github = GitHubAgent(settings, state)
    # Single pass: process whatever batch is pending, persist the offset, then
    # exit — no tight polling loop, so the Actions job always terminates.
    processed = await poll_once(settings, state, github)
    # Commit + push state (approvals decisions, telegram_offset) so the next
    # ephemeral job — and the pipeline — actually sees them. Without this, the
    # files written here vanish when the job ends and /approve would never
    # reach the outreach run.
    if processed and github.commit_state():
        log.info("state committed to repo")
    log.info("poll pass finished; processed %d update(s); exiting", processed)
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
